import type { Scene } from "@/shared/types";

export const SCENES: Scene[] = [
  {
    id: "kitchen",
    name: "Kitchen",
    icon: "restaurant",
    backgroundColor: "#FFF8E1",
    hotspots: [
      { id: "k-water", label: "Water", arasaacId: 32464, x: 10, y: 20 },
      { id: "k-milk", label: "Milk", arasaacId: 2445, x: 30, y: 20 },
      { id: "k-juice", label: "Juice", arasaacId: 11461, x: 50, y: 20 },
      { id: "k-apple", label: "Apple", arasaacId: 2462, x: 70, y: 20 },
      { id: "k-bread", label: "Bread", arasaacId: 2494, x: 10, y: 50 },
      { id: "k-eat", label: "Eat", arasaacId: 6456, x: 30, y: 50 },
      { id: "k-drink", label: "Drink", arasaacId: 6061, x: 50, y: 50 },
      { id: "k-cookie", label: "Cookie", arasaacId: 8312, x: 70, y: 50 },
      { id: "k-hungry", label: "Hungry", arasaacId: 4962, x: 20, y: 80 },
      { id: "k-more", label: "More", arasaacId: 5508, x: 40, y: 80 },
      { id: "k-alldone", label: "All Done", arasaacId: 28429, x: 60, y: 80 },
    ],
  },
  {
    id: "bedroom",
    name: "Bedroom",
    icon: "moon",
    backgroundColor: "#E8EAF6",
    hotspots: [
      { id: "b-sleep", label: "Sleep", arasaacId: 6479, x: 10, y: 20 },
      { id: "b-wakeup", label: "Wake Up", arasaacId: 8989, x: 30, y: 20 },
      { id: "b-bedtime", label: "Bedtime", arasaacId: 6479, x: 50, y: 20 },
      { id: "b-nap", label: "Nap", arasaacId: 28425, x: 70, y: 20 },
      { id: "b-book", label: "Read Book", arasaacId: 7141, x: 10, y: 50 },
      { id: "b-hug", label: "Hug", arasaacId: 4550, x: 30, y: 50 },
      { id: "b-goodnight", label: "Good Night", arasaacId: 6942, x: 50, y: 50 },
      { id: "b-tired", label: "Tired", arasaacId: 35537, x: 70, y: 50 },
      { id: "b-light", label: "Light", vocalization: "Turn on light", arasaacId: 2300, x: 20, y: 80 },
      { id: "b-scared", label: "Scared", arasaacId: 35535, x: 50, y: 80 },
    ],
  },
  {
    id: "playground",
    name: "Playground",
    icon: "sunny",
    backgroundColor: "#E8F5E9",
    hotspots: [
      { id: "p-play", label: "Play", arasaacId: 23392, x: 10, y: 20 },
      { id: "p-go", label: "Go", arasaacId: 8142, x: 30, y: 20 },
      { id: "p-run", label: "Run", vocalization: "Let's run!", arasaacId: 29951, x: 50, y: 20 },
      { id: "p-friend", label: "Friend", arasaacId: 25790, x: 70, y: 20 },
      { id: "p-myturn", label: "My Turn", arasaacId: 6006, x: 10, y: 50 },
      { id: "p-again", label: "Again!", arasaacId: 37163, x: 30, y: 50 },
      { id: "p-letsgo", label: "Let's Go!", arasaacId: 8142, x: 50, y: 50 },
      { id: "p-wait", label: "Wait", arasaacId: 36914, x: 70, y: 50 },
      { id: "p-happy", label: "Happy", arasaacId: 35533, x: 15, y: 80 },
      { id: "p-excited", label: "Excited!", arasaacId: 39090, x: 40, y: 80 },
      { id: "p-stop", label: "Stop", arasaacId: 7196, x: 65, y: 80 },
    ],
  },
  {
    id: "bathroom",
    name: "Bathroom",
    icon: "water",
    backgroundColor: "#E0F7FA",
    hotspots: [
      { id: "ba-bath", label: "Bath", arasaacId: 2272, x: 10, y: 20 },
      { id: "ba-brush", label: "Brush Teeth", arasaacId: 2326, x: 35, y: 20 },
      { id: "ba-wash", label: "Wash Hands", arasaacId: 9006, x: 60, y: 20 },
      { id: "ba-diaper", label: "Diaper", arasaacId: 22017, x: 10, y: 50 },
      { id: "ba-water", label: "Water", arasaacId: 32464, x: 35, y: 50 },
      { id: "ba-help", label: "Help Me", arasaacId: 4570, x: 60, y: 50 },
      { id: "ba-alldone", label: "All Done", arasaacId: 28429, x: 20, y: 80 },
      { id: "ba-cold", label: "Cold", arasaacId: 4652, x: 45, y: 80 },
      { id: "ba-hot", label: "Hot", arasaacId: 2300, x: 65, y: 80 },
    ],
  },
  {
    id: "mealtime",
    name: "Mealtime",
    icon: "cafe",
    backgroundColor: "#FFF3E0",
    hotspots: [
      { id: "m-eat", label: "Eat", arasaacId: 6456, x: 10, y: 20 },
      { id: "m-drink", label: "Drink", arasaacId: 6061, x: 30, y: 20 },
      { id: "m-milk", label: "Milk", arasaacId: 2445, x: 50, y: 20 },
      { id: "m-rice", label: "Rice", arasaacId: 6911, x: 70, y: 20 },
      { id: "m-chicken", label: "Chicken", arasaacId: 4952, x: 10, y: 50 },
      { id: "m-banana", label: "Banana", arasaacId: 2530, x: 30, y: 50 },
      { id: "m-egg", label: "Egg", arasaacId: 2427, x: 50, y: 50 },
      { id: "m-pizza", label: "Pizza", arasaacId: 2527, x: 70, y: 50 },
      { id: "m-more", label: "More", arasaacId: 5508, x: 15, y: 80 },
      { id: "m-hungry", label: "Hungry", arasaacId: 4962, x: 40, y: 80 },
      { id: "m-alldone", label: "All Done", arasaacId: 28429, x: 65, y: 80 },
    ],
  },
  {
    id: "school",
    name: "School",
    icon: "school",
    backgroundColor: "#E3F2FD",
    hotspots: [
      { id: "sc-teacher", label: "Teacher", arasaacId: 6556, x: 10, y: 20 },
      { id: "sc-friend", label: "Friend", arasaacId: 25790, x: 30, y: 20 },
      { id: "sc-read", label: "Read", arasaacId: 7141, x: 50, y: 20 },
      { id: "sc-write", label: "Write", vocalization: "I want to write", arasaacId: 32751, x: 70, y: 20 },
      { id: "sc-help", label: "Help", arasaacId: 32648, x: 10, y: 50 },
      { id: "sc-play", label: "Play", arasaacId: 23392, x: 30, y: 50 },
      { id: "sc-bathroom", label: "Bathroom", vocalization: "I need the bathroom", arasaacId: 5921, x: 50, y: 50 },
      { id: "sc-myturn", label: "My Turn", arasaacId: 6006, x: 70, y: 50 },
      { id: "sc-good", label: "Good", arasaacId: 4581, x: 15, y: 80 },
      { id: "sc-wait", label: "Wait", arasaacId: 36914, x: 40, y: 80 },
      { id: "sc-alldone", label: "All Done", arasaacId: 28429, x: 65, y: 80 },
    ],
  },
  {
    id: "park",
    name: "Park",
    icon: "leaf",
    backgroundColor: "#E8F5E9",
    hotspots: [
      { id: "pk-swing", label: "Swing", vocalization: "I want to swing", arasaacId: 23392, x: 10, y: 20 },
      { id: "pk-slide", label: "Slide", vocalization: "Let's go on the slide", arasaacId: 8142, x: 35, y: 20 },
      { id: "pk-run", label: "Run", arasaacId: 29951, x: 60, y: 20 },
      { id: "pk-walk", label: "Walk", arasaacId: 29951, x: 10, y: 50 },
      { id: "pk-friend", label: "Friend", arasaacId: 25790, x: 35, y: 50 },
      { id: "pk-dog", label: "Dog", vocalization: "Look, a dog!", arasaacId: 2339, x: 60, y: 50 },
      { id: "pk-happy", label: "Happy", arasaacId: 35533, x: 15, y: 80 },
      { id: "pk-more", label: "More", arasaacId: 5508, x: 40, y: 80 },
      { id: "pk-letsgo", label: "Let's Go", arasaacId: 8142, x: 65, y: 80 },
    ],
  },
  {
    id: "doctor",
    name: "Doctor",
    icon: "medkit",
    backgroundColor: "#FCE4EC",
    hotspots: [
      { id: "dr-doctor", label: "Doctor", arasaacId: 6561, x: 10, y: 20 },
      { id: "dr-sick", label: "Sick", arasaacId: 7040, x: 30, y: 20 },
      { id: "dr-hurt", label: "Hurt", vocalization: "It hurts", arasaacId: 7040, x: 50, y: 20 },
      { id: "dr-scared", label: "Scared", arasaacId: 35535, x: 70, y: 20 },
      { id: "dr-help", label: "Help Me", arasaacId: 4570, x: 10, y: 50 },
      { id: "dr-mom", label: "Mom", arasaacId: 2458, x: 30, y: 50 },
      { id: "dr-dad", label: "Dad", arasaacId: 2497, x: 50, y: 50 },
      { id: "dr-water", label: "Water", arasaacId: 32464, x: 70, y: 50 },
      { id: "dr-good", label: "Good", arasaacId: 4581, x: 20, y: 80 },
      { id: "dr-alldone", label: "All Done", arasaacId: 28429, x: 50, y: 80 },
    ],
  },
  {
    id: "store",
    name: "Store",
    icon: "cart",
    backgroundColor: "#F3E5F5",
    hotspots: [
      { id: "st-want", label: "Want", arasaacId: 5441, x: 10, y: 20 },
      { id: "st-apple", label: "Apple", arasaacId: 2462, x: 30, y: 20 },
      { id: "st-banana", label: "Banana", arasaacId: 2530, x: 50, y: 20 },
      { id: "st-cookie", label: "Cookie", arasaacId: 8312, x: 70, y: 20 },
      { id: "st-milk", label: "Milk", arasaacId: 2445, x: 10, y: 50 },
      { id: "st-bread", label: "Bread", arasaacId: 2494, x: 30, y: 50 },
      { id: "st-please", label: "Please", arasaacId: 8195, x: 50, y: 50 },
      { id: "st-thankyou", label: "Thank You", arasaacId: 8129, x: 70, y: 50 },
      { id: "st-more", label: "More", arasaacId: 5508, x: 20, y: 80 },
      { id: "st-alldone", label: "All Done", arasaacId: 28429, x: 50, y: 80 },
    ],
  },
];
